version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}


  adminer: # db 클라이언트
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  springboot:
    container_name: springboot
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file: ./.env


